### PR TITLE
Fix invalid cargo key for docs.rs

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of gtk-rs/gir#845

cc @sdroege @EPashkin @sfanxiang

### CODE REVIEW

**Comment by EPashkin** [comment]
👍

**Comment by sfanxiang** [comment]
Thanks @GuillaumeGomez!

**Comment by sfanxiang** [comment]
Correct me if I'm wrong: should this be merged to gtk4, gsk4, graphene and maybe gtk as well?

**Comment by GuillaumeGomez** [comment]
I'm going through crates at my own pace. :)

**Pull request merged**
